#!/bin/bash

# Add source command to .bashrc
if [ -f ~/.bashrc ]; then
    echo "source ~/.cfg/${DOTFILES_ACTIVE_CONFIG}/default/bash/rc" >> ~/.bashrc
    echo "export PATH=\"\$HOME/.cfg/${DOTFILES_ACTIVE_CONFIG}/bin:\$PATH\"" >> ~/.bashrc
fi

# Copy configuration
cp -r ~/.cfg/shared/config/* ~/.config/
cp -r ~/.cfg/omarchy/config/* ~/.config/