#!/bin/bash

# Add source command to .bashrc
if [ -f ~/.bashrc ]; then
    echo "source ~/.cfg/omakasui/default/bash/rc" >> ~/.bashrc
    echo "export PATH=\"\$HOME/.cfg/omakasui/bin:\$PATH\"" >> ~/.bashrc
fi

# Copy configuration
cp -r ~/.cfg/omakasui/config/* ~/.config/